services:
  - type: web
    name: expense-tracker-api
    env: docker
    region: oregon # or frankfurt/london depending on your preference
    plan: free
    autoDeploy: true

    # Optional: only include if you need to set ports explicitly
    envVars:
      - key: PORT
        value: 5000

    # Optional: set environment variables for database or other secrets
    # - key: ConnectionStrings__DefaultConnection
    #   value: YOUR_MYSQL_CONNECTION_STRING
